# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/seekdialogue.ui',
# licensing of 'qt/seekdialogue.ui' applies.
#
# Created: Sun Mar  3 05:41:17 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_SeekDialogue(object):
    def setupUi(self, SeekDialogue):
        SeekDialogue.setObjectName("SeekDialogue")
        SeekDialogue.resize(300, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SeekDialogue.sizePolicy().hasHeightForWidth())
        SeekDialogue.setSizePolicy(sizePolicy)
        SeekDialogue.setMinimumSize(QtCore.QSize(300, 200))
        self.gridLayout = QtWidgets.QGridLayout(SeekDialogue)
        self.gridLayout.setObjectName("gridLayout")
        self.grid = QtWidgets.QGridLayout()
        self.grid.setSpacing(5)
        self.grid.setContentsMargins(5, 5, 5, 5)
        self.grid.setObjectName("grid")
        self.hour_label = QtWidgets.QLabel(SeekDialogue)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.hour_label.setFont(font)
        self.hour_label.setAlignment(QtCore.Qt.AlignCenter)
        self.hour_label.setMargin(4)
        self.hour_label.setObjectName("hour_label")
        self.grid.addWidget(self.hour_label, 1, 0, 1, 1)
        self.sec_label = QtWidgets.QLabel(SeekDialogue)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.sec_label.setFont(font)
        self.sec_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sec_label.setMargin(4)
        self.sec_label.setObjectName("sec_label")
        self.grid.addWidget(self.sec_label, 1, 2, 1, 1)
        self.hour_dial = QtWidgets.QDial(SeekDialogue)
        self.hour_dial.setObjectName("hour_dial")
        self.grid.addWidget(self.hour_dial, 2, 0, 1, 1)
        self.min_dial = QtWidgets.QDial(SeekDialogue)
        self.min_dial.setMaximum(59)
        self.min_dial.setObjectName("min_dial")
        self.grid.addWidget(self.min_dial, 2, 1, 1, 1)
        self.buttons = QtWidgets.QDialogButtonBox(SeekDialogue)
        self.buttons.setOrientation(QtCore.Qt.Horizontal)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttons.setCenterButtons(True)
        self.buttons.setObjectName("buttons")
        self.grid.addWidget(self.buttons, 5, 0, 1, 3)
        self.min_label = QtWidgets.QLabel(SeekDialogue)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.min_label.setFont(font)
        self.min_label.setAlignment(QtCore.Qt.AlignCenter)
        self.min_label.setMargin(4)
        self.min_label.setObjectName("min_label")
        self.grid.addWidget(self.min_label, 1, 1, 1, 1)
        self.min_lcd = QtWidgets.QLCDNumber(SeekDialogue)
        self.min_lcd.setDigitCount(2)
        self.min_lcd.setMode(QtWidgets.QLCDNumber.Oct)
        self.min_lcd.setObjectName("min_lcd")
        self.grid.addWidget(self.min_lcd, 3, 1, 1, 1)
        self.sec_dial = QtWidgets.QDial(SeekDialogue)
        self.sec_dial.setMaximum(59)
        self.sec_dial.setInvertedAppearance(True)
        self.sec_dial.setInvertedControls(False)
        self.sec_dial.setObjectName("sec_dial")
        self.grid.addWidget(self.sec_dial, 2, 2, 1, 1)
        self.sec_lcd = QtWidgets.QLCDNumber(SeekDialogue)
        self.sec_lcd.setDigitCount(2)
        self.sec_lcd.setMode(QtWidgets.QLCDNumber.Oct)
        self.sec_lcd.setObjectName("sec_lcd")
        self.grid.addWidget(self.sec_lcd, 3, 2, 1, 1)
        self.hour_lcd = QtWidgets.QLCDNumber(SeekDialogue)
        self.hour_lcd.setDigitCount(3)
        self.hour_lcd.setMode(QtWidgets.QLCDNumber.Oct)
        self.hour_lcd.setObjectName("hour_lcd")
        self.grid.addWidget(self.hour_lcd, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 15, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.grid.addItem(spacerItem, 4, 0, 1, 3)
        self.gridLayout.addLayout(self.grid, 0, 0, 1, 1)

        self.retranslateUi(SeekDialogue)
        QtCore.QObject.connect(self.buttons, QtCore.SIGNAL("accepted()"), SeekDialogue.accept)
        QtCore.QObject.connect(self.buttons, QtCore.SIGNAL("rejected()"), SeekDialogue.reject)
        QtCore.QMetaObject.connectSlotsByName(SeekDialogue)

    def retranslateUi(self, SeekDialogue):
        SeekDialogue.setWindowTitle(QtWidgets.QApplication.translate("SeekDialogue", "Seek", None, -1))
        self.hour_label.setText(QtWidgets.QApplication.translate("SeekDialogue", "Hours", None, -1))
        self.sec_label.setText(QtWidgets.QApplication.translate("SeekDialogue", "Seconds", None, -1))
        self.min_label.setText(QtWidgets.QApplication.translate("SeekDialogue", "Minutes", None, -1))
        self.min_lcd.setToolTip(QtWidgets.QApplication.translate("SeekDialogue", "The minutes, in octal, of the position to seek.", None, -1))
        self.sec_lcd.setToolTip(QtWidgets.QApplication.translate("SeekDialogue", "The seconds, in octal, of the position to seek.", None, -1))
        self.hour_lcd.setToolTip(QtWidgets.QApplication.translate("SeekDialogue", "The hours, in octal, of the position to seek.", None, -1))

