'''sorry for not adding comments or making code look nice, it was generated by designer :0'''


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 481)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Add = QtWidgets.QPushButton(self.centralwidget)
        self.Add.setGeometry(QtCore.QRect(0, 0, 51, 20))
        self.Add.clicked.connect(self.add_item)
        self.Add.setObjectName("Add")
        self.Remove = QtWidgets.QPushButton(self.centralwidget)
        self.Remove.setGeometry(QtCore.QRect(50, 0, 61, 20))
        self.Remove.setObjectName("Remove")
        self.Edit = QtWidgets.QPushButton(self.centralwidget)
        self.Edit.setGeometry(QtCore.QRect(110, 0, 51, 20))
        self.Edit.setObjectName("Edit")
        self.MoveUp = QtWidgets.QPushButton(self.centralwidget)
        self.MoveUp.setGeometry(QtCore.QRect(160, 0, 71, 20))
        self.MoveUp.setObjectName("MoveUp")
        self.MoveDown = QtWidgets.QPushButton(self.centralwidget)
        self.MoveDown.setGeometry(QtCore.QRect(230, 0, 71, 20))
        self.MoveDown.setObjectName("MoveDown")
        self.Objects = QtWidgets.QListWidget(self.centralwidget)
        self.Objects.setGeometry(QtCore.QRect(0, 21, 641, 441))
        self.Objects.setObjectName("Objects")
        item = QtWidgets.QListWidgetItem()
        self.Objects.addItem(item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuPlugins = QtWidgets.QMenu(self.menubar)
        self.menuPlugins.setObjectName("menuPlugins")
        self.menuItem = QtWidgets.QMenu(self.menubar)
        self.menuItem.setObjectName("menuItem")
        MainWindow.setMenuBar(self.menubar)
        self.actionAdd = QtWidgets.QAction(MainWindow)
        self.actionAdd.setObjectName("actionAdd")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.action_todo = QtWidgets.QAction(MainWindow)
        self.action_todo.setObjectName("action_todo")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionAdd_2 = QtWidgets.QAction(MainWindow)
        self.actionAdd_2.setObjectName("actionAdd_2")
        self.actionRemove = QtWidgets.QAction(MainWindow)
        self.actionRemove.setObjectName("actionRemove")
        self.menuFile.addAction(self.actionSettings)
        self.menuPlugins.addAction(self.action_todo)
        self.menuItem.addAction(self.actionAdd_2)
        self.menuItem.addAction(self.actionRemove)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPlugins.menuAction())
        self.menubar.addAction(self.menuItem.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Add.setText(_translate("MainWindow", "Add"))
        self.Remove.setText(_translate("MainWindow", "Remove"))
        self.Edit.setText(_translate("MainWindow", "Edit"))
        self.MoveUp.setText(_translate("MainWindow", "Move Up"))
        self.MoveDown.setText(_translate("MainWindow", " Move Down"))


        __sortingEnabled = self.Objects.isSortingEnabled()
        self.Objects.setSortingEnabled(False)
        item = self.Objects.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        self.Objects.setSortingEnabled(__sortingEnabled)


        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuPlugins.setTitle(_translate("MainWindow", "Plugins"))
        self.menuItem.setTitle(_translate("MainWindow", "Items"))
        self.actionAdd.setText(_translate("MainWindow", "Add"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.action_todo.setText(_translate("MainWindow", "Install #todo"))
        self.actionSettings.setText(_translate("MainWindow", "Settings #todo"))
        self.actionAdd_2.setText(_translate("MainWindow", "Add #todo"))
        self.actionRemove.setText(_translate("MainWindow", "Remove #todo"))

    def add_item(self):
        item = self.Objects.item(0)
        item.setText("MainWindow", "New Item")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

