# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eula_quiz.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EulaQuizDialog(object):
    def setupUi(self, EulaQuizDialog):
        EulaQuizDialog.setObjectName("EulaQuizDialog")
        EulaQuizDialog.resize(711, 532)
        self.verticalLayoutWidget = QtWidgets.QWidget(EulaQuizDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 691, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_13.addWidget(self.label_6)
        self.quiz5_Layout = QtWidgets.QVBoxLayout()
        self.quiz5_Layout.setObjectName("quiz5_Layout")
        self.radioButton_26 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_26.setObjectName("radioButton_26")
        self.quiz5_Layout.addWidget(self.radioButton_26)
        self.radioButton_27 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_27.setObjectName("radioButton_27")
        self.quiz5_Layout.addWidget(self.radioButton_27)
        self.quiz5_Correct = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.quiz5_Correct.setObjectName("quiz5_Correct")
        self.quiz5_Layout.addWidget(self.quiz5_Correct)
        self.radioButton_29 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_29.setObjectName("radioButton_29")
        self.quiz5_Layout.addWidget(self.radioButton_29)
        self.radioButton_30 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_30.setObjectName("radioButton_30")
        self.quiz5_Layout.addWidget(self.radioButton_30)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.quiz5_Layout.addItem(spacerItem)
        self.verticalLayout_13.addLayout(self.quiz5_Layout)
        self.gridLayout.addLayout(self.verticalLayout_13, 3, 0, 1, 1)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_15.addWidget(self.label_7)
        self.quiz6_Layout = QtWidgets.QVBoxLayout()
        self.quiz6_Layout.setObjectName("quiz6_Layout")
        self.radioButton_31 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_31.setObjectName("radioButton_31")
        self.quiz6_Layout.addWidget(self.radioButton_31)
        self.radioButton_32 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_32.setObjectName("radioButton_32")
        self.quiz6_Layout.addWidget(self.radioButton_32)
        self.radioButton_33 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_33.setObjectName("radioButton_33")
        self.quiz6_Layout.addWidget(self.radioButton_33)
        self.radioButton_34 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_34.setObjectName("radioButton_34")
        self.quiz6_Layout.addWidget(self.radioButton_34)
        self.quiz6_Correct = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.quiz6_Correct.setObjectName("quiz6_Correct")
        self.quiz6_Layout.addWidget(self.quiz6_Correct)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.quiz6_Layout.addItem(spacerItem1)
        self.verticalLayout_15.addLayout(self.quiz6_Layout)
        self.gridLayout.addLayout(self.verticalLayout_15, 3, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.quiz1_Layout = QtWidgets.QVBoxLayout()
        self.quiz1_Layout.setObjectName("quiz1_Layout")
        self.radioButton_16 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_16.setObjectName("radioButton_16")
        self.quiz1_Layout.addWidget(self.radioButton_16)
        self.quiz1_Correct = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.quiz1_Correct.setObjectName("quiz1_Correct")
        self.quiz1_Layout.addWidget(self.quiz1_Correct)
        self.radioButton_18 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_18.setObjectName("radioButton_18")
        self.quiz1_Layout.addWidget(self.radioButton_18)
        self.radioButton_19 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_19.setObjectName("radioButton_19")
        self.quiz1_Layout.addWidget(self.radioButton_19)
        self.radioButton_20 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_20.setObjectName("radioButton_20")
        self.quiz1_Layout.addWidget(self.radioButton_20)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.quiz1_Layout.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.quiz1_Layout)
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.quiz3_Layout = QtWidgets.QVBoxLayout()
        self.quiz3_Layout.setObjectName("quiz3_Layout")
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.quiz3_Layout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.quiz3_Layout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.quiz3_Layout.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_4.setObjectName("radioButton_4")
        self.quiz3_Layout.addWidget(self.radioButton_4)
        self.quiz3_Correct = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.quiz3_Correct.setObjectName("quiz3_Correct")
        self.quiz3_Layout.addWidget(self.quiz3_Correct)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.quiz3_Layout.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.quiz3_Layout)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.quiz2_Layout = QtWidgets.QVBoxLayout()
        self.quiz2_Layout.setObjectName("quiz2_Layout")
        self.radioButton_11 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_11.setObjectName("radioButton_11")
        self.quiz2_Layout.addWidget(self.radioButton_11)
        self.radioButton_12 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_12.setObjectName("radioButton_12")
        self.quiz2_Layout.addWidget(self.radioButton_12)
        self.radioButton_13 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_13.setObjectName("radioButton_13")
        self.quiz2_Layout.addWidget(self.radioButton_13)
        self.radioButton_14 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_14.setObjectName("radioButton_14")
        self.quiz2_Layout.addWidget(self.radioButton_14)
        self.quiz2_Correct = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.quiz2_Correct.setObjectName("quiz2_Correct")
        self.quiz2_Layout.addWidget(self.quiz2_Correct)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.quiz2_Layout.addItem(spacerItem4)
        self.verticalLayout_6.addLayout(self.quiz2_Layout)
        self.gridLayout.addLayout(self.verticalLayout_6, 1, 1, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_11.addWidget(self.label_5)
        self.quiz4_Layout = QtWidgets.QVBoxLayout()
        self.quiz4_Layout.setObjectName("quiz4_Layout")
        self.radioButton_21 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_21.setObjectName("radioButton_21")
        self.quiz4_Layout.addWidget(self.radioButton_21)
        self.radioButton_22 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_22.setObjectName("radioButton_22")
        self.quiz4_Layout.addWidget(self.radioButton_22)
        self.radioButton_23 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_23.setObjectName("radioButton_23")
        self.quiz4_Layout.addWidget(self.radioButton_23)
        self.radioButton_24 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_24.setObjectName("radioButton_24")
        self.quiz4_Layout.addWidget(self.radioButton_24)
        self.quiz4_Correct = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.quiz4_Correct.setObjectName("quiz4_Correct")
        self.quiz4_Layout.addWidget(self.quiz4_Correct)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.quiz4_Layout.addItem(spacerItem5)
        self.verticalLayout_11.addLayout(self.quiz4_Layout)
        self.gridLayout.addLayout(self.verticalLayout_11, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.submitButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.submitButton.setObjectName("submitButton")
        self.horizontalLayout.addWidget(self.submitButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(EulaQuizDialog)
        QtCore.QMetaObject.connectSlotsByName(EulaQuizDialog)

        # Crocpad++ modifications below
        self.submitButton.clicked.connect(self.submitClicked)
        self.question_1 = QtWidgets.QButtonGroup()
        self.question_2 = QtWidgets.QButtonGroup()
        self.question_3 = QtWidgets.QButtonGroup()
        self.question_4 = QtWidgets.QButtonGroup()
        self.question_5 = QtWidgets.QButtonGroup()
        self.question_6 = QtWidgets.QButtonGroup()
        self.question_1.addButton(self.radioButton_16)
        self.question_1.addButton(self.quiz1_Correct)
        self.question_1.addButton(self.radioButton_18)
        self.question_1.addButton(self.radioButton_19)
        self.question_1.addButton(self.radioButton_20)
        self.question_2.addButton(self.radioButton_11)
        self.question_2.addButton(self.radioButton_12)
        self.question_2.addButton(self.radioButton_13)
        self.question_2.addButton(self.radioButton_14)
        self.question_2.addButton(self.quiz2_Correct)
        self.question_3.addButton(self.radioButton)
        self.question_3.addButton(self.radioButton_2)
        self.question_3.addButton(self.radioButton_3)
        self.question_3.addButton(self.radioButton_4)
        self.question_3.addButton(self.quiz3_Correct)
        self.question_4.addButton(self.radioButton_21)
        self.question_4.addButton(self.radioButton_22)
        self.question_4.addButton(self.radioButton_23)
        self.question_4.addButton(self.radioButton_24)
        self.question_4.addButton(self.quiz4_Correct)
        self.question_5.addButton(self.radioButton_26)
        self.question_5.addButton(self.radioButton_27)
        self.question_5.addButton(self.quiz5_Correct)
        self.question_5.addButton(self.radioButton_29)
        self.question_5.addButton(self.radioButton_30)
        self.question_6.addButton(self.radioButton_31)
        self.question_6.addButton(self.radioButton_32)
        self.question_6.addButton(self.radioButton_33)
        self.question_6.addButton(self.radioButton_34)
        self.question_6.addButton(self.quiz6_Correct)

    def submitClicked(self):
        if self.quiz_correct():
            dlg = QtWidgets.QMessageBox(self)
            dlg.setText("Correct. Thank you for using Crocpad++.")
            dlg.setIcon(QtWidgets.QMessageBox.Critical)
            dlg.show()
        self.close()

    def quiz_correct(self):
        return (self.quiz1_Correct.isChecked() and
                self.quiz2_Correct.isChecked() and
                self.quiz3_Correct.isChecked() and
                self.quiz4_Correct.isChecked() and
                self.quiz5_Correct.isChecked() and
                self.quiz6_Correct.isChecked()
                )

    def retranslateUi(self, EulaQuizDialog):
        _translate = QtCore.QCoreApplication.translate
        EulaQuizDialog.setWindowTitle(_translate("EulaQuizDialog", "Quiz"))
        self.label_8.setText(_translate("EulaQuizDialog", "To indicate your understanding of the Terms and Conditions of the SOFTWARE, you must pass the following mandatory quiz."))
        self.label_6.setText(_translate("EulaQuizDialog", "How are disputes between you and us to be resolved?"))
        self.radioButton_26.setText(_translate("EulaQuizDialog", "Jury trial"))
        self.radioButton_27.setText(_translate("EulaQuizDialog", "Trial by judge"))
        self.quiz5_Correct.setText(_translate("EulaQuizDialog", "Arbitration, with an arbitrator chosen by us"))
        self.radioButton_29.setText(_translate("EulaQuizDialog", "Violence"))
        self.radioButton_30.setText(_translate("EulaQuizDialog", "None of the above"))
        self.label_7.setText(_translate("EulaQuizDialog", "What must the SOFTWARE do for you?"))
        self.radioButton_31.setText(_translate("EulaQuizDialog", "Be fit for any particular purpose"))
        self.radioButton_32.setText(_translate("EulaQuizDialog", "Be responsible for the integrity of your data"))
        self.radioButton_33.setText(_translate("EulaQuizDialog", "Convey liability from use or inability to use"))
        self.radioButton_34.setText(_translate("EulaQuizDialog", "Not send your files over the internet"))
        self.quiz6_Correct.setText(_translate("EulaQuizDialog", "None of the above"))
        self.label_4.setText(_translate("EulaQuizDialog", "When did I agree to the Terms and Conditions?"))
        self.radioButton_16.setText(_translate("EulaQuizDialog", "When I clicked Agree"))
        self.quiz1_Correct.setText(_translate("EulaQuizDialog", "When I launched the SOFTWARE"))
        self.radioButton_18.setText(_translate("EulaQuizDialog", "When I downloaded the SOFTWARE"))
        self.radioButton_19.setText(_translate("EulaQuizDialog", "I did not agree"))
        self.radioButton_20.setText(_translate("EulaQuizDialog", "None of the above"))
        self.label.setText(_translate("EulaQuizDialog", "What may the SOFTWARE not be used for?"))
        self.radioButton.setText(_translate("EulaQuizDialog", "Profit"))
        self.radioButton_2.setText(_translate("EulaQuizDialog", "Non-profit"))
        self.radioButton_3.setText(_translate("EulaQuizDialog", "Information"))
        self.radioButton_4.setText(_translate("EulaQuizDialog", "Entertainment"))
        self.quiz3_Correct.setText(_translate("EulaQuizDialog", "All of the above"))
        self.label_3.setText(_translate("EulaQuizDialog", "When may we share your data with law enforcement?"))
        self.radioButton_11.setText(_translate("EulaQuizDialog", "When legally required"))
        self.radioButton_12.setText(_translate("EulaQuizDialog", "When not legally required"))
        self.radioButton_13.setText(_translate("EulaQuizDialog", "If the data is critical of law enforcement"))
        self.radioButton_14.setText(_translate("EulaQuizDialog", "If they might like it"))
        self.quiz2_Correct.setText(_translate("EulaQuizDialog", "All of the above"))
        self.label_5.setText(_translate("EulaQuizDialog", "How may we use your data?"))
        self.radioButton_21.setText(_translate("EulaQuizDialog", "Read it"))
        self.radioButton_22.setText(_translate("EulaQuizDialog", "Sell it"))
        self.radioButton_23.setText(_translate("EulaQuizDialog", "Auction it"))
        self.radioButton_24.setText(_translate("EulaQuizDialog", "Polymorph it"))
        self.quiz4_Correct.setText(_translate("EulaQuizDialog", "All of the above"))
        self.submitButton.setText(_translate("EulaQuizDialog", "Submit"))

